# Generated by Django 2.2.5 on 2019-09-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TreeID', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=50)),
                ('CommonName', models.CharField(max_length=100)),
                ('ScientificName', models.CharField(max_length=100)),
                ('TrunkDiameter', models.IntegerField(default=0)),
                ('TreeHeight', models.IntegerField(default=0)),
                ('DatePlanted', models.DateTimeField(auto_now=True)),
                ('DateRemoved', models.DateTimeField(auto_now=True)),
                ('Condition', models.CharField(max_length=100)),
                ('DiameterMeasurementMethod', models.CharField(max_length=100)),
                ('Project', models.CharField(max_length=100)),
                ('TreeStewardship', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Pincode', models.IntegerField(default=0)),
            ],
        ),
    ]
