# Generated by Django 2.2.5 on 2019-09-07 06:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemapping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treedata',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='treedata',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='treedata',
            old_name='CommonName',
            new_name='commonName',
        ),
        migrations.RenameField(
            model_name='treedata',
            old_name='Condition',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='treedata',
            old_name='DatePlanted',
            new_name='datePlanted',
        ),
        migrations.RenameField(
            model_name='treedata',
            old_name='DiameterMeasurementMethod',
            new_name='scientificName',
        ),
        migrations.RenameField(
            model_name='treedata',
            old_name='Project',
            new_name='treeStewardship',
        ),
        migrations.RenameField(
            model_name='treedata',
            old_name='Pincode',
            new_name='trunkDiameter',
        ),
        migrations.RemoveField(
            model_name='treedata',
            name='DateRemoved',
        ),
        migrations.RemoveField(
            model_name='treedata',
            name='ScientificName',
        ),
        migrations.RemoveField(
            model_name='treedata',
            name='TreeStewardship',
        ),
        migrations.RemoveField(
            model_name='treedata',
            name='TrunkDiameter',
        ),
        migrations.AddField(
            model_name='treedata',
            name='pincode',
            field=models.IntegerField(default=413405),
        ),
        migrations.AlterField(
            model_name='treedata',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
