# Generated by Django 2.2.5 on 2019-09-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemapping', '0002_auto_20190907_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treedata',
            old_name='TreeHeight',
            new_name='treeHeight',
        ),
        migrations.RenameField(
            model_name='treedata',
            old_name='TreeID',
            new_name='treeID',
        ),
    ]
